export const ADD_TO_CART = 'addToCart'
export const REMOVE_FROM_CART = 'removeFromCart'
export const INCREASE_AMOUNT = 'increaseAmount'
export const DECREASE_AMOUNT = 'decreaseAmount'
export const GET_TOTALS = 'getTotals'
export const RESET_CART = 'resetCart'